services:
  - type: web
    name: project-bolt-backend
    env: node
    buildCommand: npm run build:server
    startCommand: npm run start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: NODE_ENV
        value: production 