services:
  - type: web
    name: project-bolt-backend
    env: node
    buildCommand: |
      npm install
      npm run build
      npm run build:server
      mkdir -p /opt/render/project/src/dist
      cp -r dist/* /opt/render/project/src/dist/
      cp -r dist/server /opt/render/project/src/dist/
      chmod -R 755 /opt/render/project/src/dist
      ls -la /opt/render/project/src/dist
    startCommand: npm run start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: NODE_ENV
        value: production 